### ISSUE TITLE
syncthing-cli stopped working

### ISSUE THREAD

**Issue by zilti** [syncthing/syncthing-cli#10]
Since the latest update of Syncthing, syncthing-cli doesn't work anymore. All I get is

```
Get http://127.0.0.1:8080: dial tcp 127.0.0.1:8080: connection refused
```

How can I fix that?

**Comment by AudriusButkevicius** [comment]
Check your web UI port.
If you are using latest syncthing, it uses a different port 8384, you can cli to use that, see `-help`.

**Comment by zilti** [comment]
I'm not using the latest beta. My version is `syncthing v0.10.30 (go1.4.2 freebsd-amd64 default)`, and it also still uses port 8080.

**Comment by AudriusButkevicius** [comment]
Well, then syncthing is not listening on that port.

**Comment by zilti** [comment]
It is. When I launch Syncthing, it even puts that exact address in the logs.

**Comment by AudriusButkevicius** [comment]
And can you actually access that via the web browser?
