### ISSUE TITLE
Add `filestatus` command

### ISSUE THREAD

**Issue by allanbreyes** [syncthing/syncthing-cli#15]
Definitely an enhancement...  I'm looking for something similar to Dropbox's CLI command `filestatus` - http://www.dropboxwiki.com/tips-and-tricks/using-the-official-dropbox-command-line-interface-cli#Getting_Started

Would be great for terminal scripts/prompts.  I use Dropbox's CLI in ZSH terminal to get some feedback... would love to have it with Syncthing:

```
# user@machine: ~/Sync syncthing:✔ 
$ touch 1.txt 2.txt 3.txt

# user@machine: ~/Sync syncthing:↻ 
$ syncthing-cli filestatus
1.txt: syncing
2.txt: syncing
3.txt: syncing

# user@machine: ~/Sync syncthing:✔
$ syncthing-cli filestatus
1.txt: up to date
2.txt: up to date
3.txt: up to date
```

Wish I could help contribute, but I don't know golang :(  Great work, though!  Lovin' it!

**Comment by AudriusButkevicius** [comment]
First of all, there are people who have 10 million files (ref http://data.syncthing.net/) so it would only make sense to list files which are unsynced.

So the fact that you don't know golang is a poor excuse, adding a command to the CLI is very trivial especially as there already multiple implementation examples that you can easily follow.

Given you are interested, the need call (http://docs.syncthing.net/rest/db-need-get.html) is probably what you are after, as I personally have no need for this - hence no plans to implement this.

**Comment by AudriusButkevicius** [comment]
Reopening as it is a valid enhancement.
Someone just needs to dedicate some time.

**Comment by calmh** [comment]
This is roughly the number one thing I want to get into stcli and the reason I moved it into the main repo. Will get solved when it gets solved, I *promise*!
