### ISSUE TITLE
device address format validation error

### ISSUE THREAD

**Issue by boormat** [syncthing/syncthing-cli#22]
The set device address validation only accepts a hostname:port, and rejects a TCP URL.
Syncthing expects a url style,  tcp://hostname:port.

Adding new device from the cli that needs an address as below results in a device in syncthing that does not work, until address is manually corrected in syncthing GUI.

```
syncthing-cli devices add DEVICE
syncthing-cli devices set DEVICE name whatever
syncthing-cli devices set DEVICE address HOST:PORT
```

**Comment by AudriusButkevicius** [comment]
Yeah, this is know, as the cli works against a very old API.
It hasn't had much traction, hence any external effort to help fix these is welcome.

**Comment by calmh** [comment]
Tralalala closing as part of general closing spree, now lives in main repo, will get fixed at some point I promise(ish)
