### ISSUE TITLE
Can not connect via HTTPS

### ISSUE THREAD

**Issue by cdpb** [syncthing/syncthing-cli#23]
it's seems that #3 is not fixed completly.

```
$ syncthing-cli -e https://127.0.0.1:8080 -u admin -p <...> status
Get https://127.0.0.1:8080: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

I have to append `-i`
```
$ syncthing-cli -e https://127.0.0.1:8080 -i -u admin -p <...> status
Config in sync
```

I'm not really sure how to handle this, is my inital ssl certificate, created by syncthing invalid or is it just a bug in the syncthing-cli binary?

I just build syncthing-cli from source for GOARCH arm

**Comment by AudriusButkevicius** [comment]
If you are using a self signed certificat (which you mist likely are), you need the -i option for insecure, just as explained in the -help

**Comment by cdpb** [comment]
okay, I understand, but I also test it on another machine, also with self signed certificates and I didn't have to set -i option, so I assumed a bug

**Comment by AudriusButkevicius** [comment]
No, if you don't have validation errors on another machine, something is wrong with that machine, as all certificates syncthing generates are self singed. It's only possible if you replaced the certificate with a non-self-signed one yourself.

**Comment by cdpb** [comment]
okay, thank you
