### ISSUE TITLE
Unable to set master property

### ISSUE THREAD

**Issue by bear0330** [syncthing/syncthing-cli#26]
Syncthing version, 0.14.4, syncthing-cli (latest build)

```
[root@nuwa-test ~]# syncthing-cli -k $SYNCTHING_API_KEY folders set `hostname`-backup master true
[root@nuwa-test ~]# syncthing-cli -k $SYNCTHING_API_KEY folders get `hostname`-backup master
false
```

the folder type still remains 'readwrite' after I call set folder master true.

**Comment by calmh** [comment]
This project is effectively unmaintained, so unfortunately this is probably unlikely to be fixed anytime.

**Comment by calmh** [comment]
To be fixed as part of some greater overhaul in the future
