### ISSUE TITLE
build for arm (armv7l)

### ISSUE THREAD

**Issue by arthurlutz** [syncthing/syncthing-cli#27]
Hi, 

syncthing-cli is awesome, thanks for such a great useful project. 

Is there any chance of getting a build for arm in http://build.syncthing.net/job/syncthing-cli/lastSuccessfulBuild/artifact/ ? Or some cross platform build instructions for people who are not familiar with go ? 

Thanks in advance for your answer

**Comment by AudriusButkevicius** [comment]
Sadly it's somewhat unmaintained. Just can cross compile it llke any other go application
