### ISSUE TITLE
cannot build a project 

### ISSUE THREAD

**Issue by 62mkv** [syncthing/syncthing-cli#28]
As I run `go get github.com/syncthing/syncthing-cli`, this is what I get: 

> > go get github.com/syncthing/syncthing-cli
> # github.com/syncthing/syncthing-cli
> src/github.com/syncthing/syncthing-cli/cmd_folders.go:105: folder.ReadOnly undefined (type config.FolderConfiguration has no field or method ReadOnly)
> src/github.com/syncthing/syncthing-cli/cmd_folders.go:115: folder.Invalid undefined (type config.FolderConfiguration has no field or method Invalid)
> src/github.com/syncthing/syncthing-cli/cmd_folders.go:116: folder.Invalid undefined (type config.FolderConfiguration has no field or method Invalid)
> src/github.com/syncthing/syncthing-cli/cmd_folders.go:154: folder.ReadOnly undefined (type config.FolderConfiguration has no field or method ReadOnly)
> src/github.com/syncthing/syncthing-cli/cmd_folders.go:191: folder.ReadOnly undefined (type config.FolderConfiguration has no field or method ReadOnly)
> src/github.com/syncthing/syncthing-cli/cmd_folders.go:226: cfg.Folders[i].ReadOnly undefined (type config.FolderConfiguration has no field or method ReadOnly)
> src/github.com/syncthing/syncthing-cli/cmd_gui.go:95: cannot assign to cfg.GUI.UseTLS
> src/github.com/syncthing/syncthing-cli/cmd_gui.go:95: cannot use parseBool(val) (type bool) as type func() bool in assignment
> src/github.com/syncthing/syncthing-cli/cmd_gui.go:98: cannot assign to cfg.GUI.Address
> src/github.com/syncthing/syncthing-cli/cmd_gui.go:98: cannot use val (type string) as type func() string in assignment
> src/github.com/syncthing/syncthing-cli/cmd_gui.go:98: too many errors
 
My `go env`:

> GOARCH="amd64"
> GOBIN="/root/projects/bin"
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/root/projects/src"
> GORACE=""
> GOROOT="/usr/local/go"
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> CC="gcc"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build996660652=/tmp/go-build -gno-record-gcc-switches"
> CXX="g++"
> CGO_ENABLED="1"
> 
My `go version`:
> go version go1.7 linux/amd64

CentOS Linux release 7.2.1511 

Go is installed according to [this](https://www.digitalocean.com/community/tutorials/how-to-install-go-1-7-on-centos-7)
Any ideas?

**Comment by AudriusButkevicius** [comment]
This is old and unmaintained sadly. I welcome PRs fixing this.

**Comment by calmh** [comment]
It builds now, as part of the main repo, but doesn't necessarily work. I intend to get to that ... but ... so many things to get to ...
