### ISSUE TITLE
create release tag

### ISSUE THREAD

**Issue by ncopa** [syncthing/syncthing-cli#5]
It would be very helpful for packagers if there was a release tag.

https://help.github.com/articles/creating-releases/

**Comment by AudriusButkevicius** [comment]
How important is this?
I don't update this unless the build breaks due to packages moving around in syncthing.
Plus a lot of stuff has changed in syncthing breaking the cli in certain areas (mostly announce server related)

**Comment by rumpelsepp** [comment]
> How important is this?

For future releases it is useful because one could easily provide AUR packages: https://aur.archlinux.org/packages/syncthing-cli-git/

**Comment by anatol** [comment]
+1 for a release tag. This helps to bring this software to Linux distros where having non-released software is usually considered as a downsize.

**Comment by AudriusButkevicius** [comment]
This is most likely broken for v0.12. If someone cares enough to fix all the issues, I'll make a release tag.

**Comment by anatol** [comment]
@AudriusButkevicius Did it in PR #21

**Comment by terrycloth** [comment]
I was just browsing in Bountysource. We could probably close this issue, and most / all other issues in this repo, since syncthing-cli merged into the main syncthing project.

**Comment by canton7** [comment]
> syncthing-cli merged into the main syncthing project.

No it wasn't. It was more or less abandoned.

**Comment by AudriusButkevicius** [comment]
It was moved to the main repo, and yes, it has not been updated.

**Comment by calmh** [comment]
There will never be a release tag in this repo, and if there is a release there will be a tag on the other repo. 👍
