### ISSUE TITLE
Help documentation.

### ISSUE THREAD

**Issue by wizonesolutions** [syncthing/syncthing-cli#7]
When I run `syncthing folders add`, I am told it takes exactly two arguments, the folder ID and the directory.

Is it not possible to customize the versioning or sync interval in `syncthing-cli` right now? I wanted to use it to avoid having to go to the another computer and manually adjust the folder settings via the UI.

**Comment by AudriusButkevicius** [comment]
There is `folders X set ` which might help.

**Comment by wizonesolutions** [comment]
Yep, that was exactly it! I wish I could list property names, but I was able to figure them out from the other folders when I used `folders list`..
